# coding: utf-8

"""
    defaultTitle

    defaultDescription  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model0 import Model0  # noqa: E501
from swagger_client.rest import ApiException


class TestModel0(unittest.TestCase):
    """Model0 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel0(self):
        """Test Model0"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model0.Model0()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
